### ISSUE TITLE
joingenes segmentation fault 

### ISSUE THREAD

**Issue by MarioStanke** [Gaius-Augustus/Augustus#182]
First reported here:
https://github.com/Gaius-Augustus/BRAKER/issues/229

**Comment by bioinfowheat** [comment]
Hello, 
I am also having this problem with August v3.3.3

ERROR in file /data/programs/BRAKER2_v2.1.5/scripts/braker.pl at line 9481
Failed to execute: /data/programs/Augustus_v3.3.3/bin/joingenes --genesets=/mnt/griffin/marcel/Pca_genome/braker2_test/braker/augustus.E.gtf,/mnt/griffin/marcel/Pca_genome/braker2_test/braker/augustus.Ppri5.gtf_filtered --priorities=2,1 --output=/mnt/griffin/marcel/Pca_genome/braker2_test/braker/join.gtf 1> /dev/null 2> /mnt/griffin/marcel/Pca_genome/braker2_test/braker/errors/joingenes.err!

# OK, check the error file
more /mnt/griffin/marcel/Pca_genome/braker2_test/braker/errors/joingenes.err
Load warning: Did not expect feature "internal". Known features are "CDS", "UTR", "3'-UTR", "5'-UTR", "exon", "intron", "gene", "transcript", "tss", "tts", "s
tart_codon" and "stop_codon". This feature is going to be ignored.
This warning may affect the result.
Load warning: Did not expect feature "initial". Known features are "CDS", "UTR", "3'-UTR", "5'-UTR", "exon", "intron", "gene", "transcript", "tss", "tts", "st
art_codon" and "stop_codon". This feature is going to be ignored.
This warning may affect the result.
Load warning: Did not expect feature "terminal". Known features are "CDS", "UTR", "3'-UTR", "5'-UTR", "exon", "intron", "gene", "transcript", "tss", "tts", "s
tart_codon" and "stop_codon". This feature is going to be ignored.
This warning may affect the result.
Segmentation fault


# OK, so I am attempting to run this
/data/programs/Augustus_v3.3.3/bin/joingenes --genesets=/mnt/griffin/marcel/Pca_genome/braker2_test/braker/augustus.E.gtf,/mnt/griffin/marcel/Pca_genome/braker2_test/braker/augustus.Ppri5.gtf_filtered --priorities=2,1 --output=/mnt/griffin/marcel/Pca_genome/braker2_test/braker/join.gtf 1> /dev/null 2> /mnt/griffin/marcel/Pca_genome/braker2_test/braker/errors/joingenes.err
# returns
Segmentation fault

**Comment by gsilvaarias** [comment]
Hello,
I am also having this problem with `August` v3.3.3 (cloned on 23 Sept 2020) running on `Braker`
* paths removed for simplicity.

```
joingenes --genesets=augustus.E.gtf,augustus.Ppri5.gtf_filtered --priorities=2,1 --output=join.gtf
```
```
# After loading augustus.E.gtf (Priority 2) there are 106850 transcripts in transcript list.
Load warning: Did not expect feature "single". Known features are "CDS", "UTR", "3'-UTR", "5'-UTR", "exon", "intron", "gene", "transcript", "tss", "tts", "start_codon" and "stop_codon". This feature is going to be ignored.
This warning may affect the result.
Load warning: Did not expect feature "terminal". Known features are "CDS", "UTR", "3'-UTR", "5'-UTR", "exon", "intron", "gene", "transcript", "tss", "tts", "start_codon" and "stop_codon". This feature is going to be ignored.
This warning may affect the result.
Load warning: Did not expect feature "initial". Known features are "CDS", "UTR", "3'-UTR", "5'-UTR", "exon", "intron", "gene", "transcript", "tss", "tts", "start_codon" and "stop_codon". This feature is going to be ignored.
This warning may affect the result.
Load warning: Did not expect feature "internal". Known features are "CDS", "UTR", "3'-UTR", "5'-UTR", "exon", "intron", "gene", "transcript", "tss", "tts", "start_codon" and "stop_codon". This feature is going to be ignored.
This warning may affect the result.
# After loading augustus.Ppri5.gtf_filtered (Priority 1) there are 128046 transcripts in transcript list.
Segmentation fault (core dumped)
```

**Comment by MarioStanke** [comment]
A bug in joingenes that is the likely caus of this error has been fixed yesterday.

**Comment by zsdxgl** [comment]
Dear MarioStanke,
The error still exists.  What's meaning of "this error has been fixed". Which version should we use, especially augustus and braker ? Can you give clear explaination?  Thanks.
